### ISSUE TITLE
Please make the mod for fabric on 1.19

### ISSUE THREAD

**Issue by lololy100** [emmods/critical-orientation#2]

**Comment by wafflecoffee** [comment]
This mod has migrated to [Quilt](https://quiltmc.org) only for 1.19. Quilt can load Fabric mods, but Fabric cannot load Quilt mods. If you're insistent about using Fabric for whatever reason, you may use a similar mod instead - [Cardinal Ice Boats](https://modrinth.com/mod/cardinalboats).
